In [1]:
import pandas as pd
import numpy as np

In [2]:
dftuyensinh = pd.read_csv('processed_dulieuxettuyendaihoc.csv')
dftuyensinh.head()

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0

1. Xác định và phân loại dữ liệu định tính và định lượng

In [3]:
dinh_tinh = ['GT', 'DT', 'KV', 'KT']  
dinh_luong = ['T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1',
              'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2',
              'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6',
              'DH1', 'DH2', 'DH3']
print("Dữ liệu định tính:", dinh_tinh)
print("Dữ liệu định lượng:", dinh_luong)

Dữ liệu định tính: ['GT', 'DT', 'KV', 'KT']
Dữ liệu định lượng: ['T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1', 'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2', 'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6', 'DH1', 'DH2', 'DH3']

2. Định nghĩa các thang đo phù hợp cho từng biến số

In [4]:
thang_do = {var: 'Danh mục' for var in dinh_tinh}
thang_do.update({var: 'Tỷ lệ' for var in dinh_luong})
# print("Thang đo của từng biến số:", thang_do)
for var, scale in thang_do.items():
    print(f"{var}: {scale}")

GT: Danh mục
DT: Danh mục
KV: Danh mục
KT: Danh mục
T1: Tỷ lệ
L1: Tỷ lệ
H1: Tỷ lệ
S1: Tỷ lệ
V1: Tỷ lệ
X1: Tỷ lệ
D1: Tỷ lệ
N1: Tỷ lệ
T2: Tỷ lệ
L2: Tỷ lệ
H2: Tỷ lệ
S2: Tỷ lệ
V2: Tỷ lệ
X2: Tỷ lệ
D2: Tỷ lệ
N2: Tỷ lệ
T6: Tỷ lệ
L6: Tỷ lệ
H6: Tỷ lệ
S6: Tỷ lệ
V6: Tỷ lệ
X6: Tỷ lệ
D6: Tỷ lệ
N6: Tỷ lệ
DH1: Tỷ lệ
DH2: Tỷ lệ
DH3: Tỷ lệ

3. Sử dụng Python để tải dữ liệu lên chương trình và in ra màn hình 10 dòng đầu tiên và 10
dòng cuối cùng

In [5]:
dftuyensinh.head(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,7.96,8.54,7.38,K,G,K,3.184,3.416,2.952,0.0
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,4.90,5.60,6.01,Y,TB,TB,1.960,2.240,2.404,1.0
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,6.80,6.87,7.03,K,K,K,2.720,2.748,2.812,0.0
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,6.23,6.72,7.56,TB,K,K,2.492,2.688,3.024,0.0
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,6.80,7.25,7.03,K,K,K,2.720,2.900,2.812,0.0

In [6]:
dftuyensinh.tail(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
90,91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,...,7.84,8.27,8.29,K,G,G,3.136,3.308,3.316,1.0
91,92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,...,6.17,6.63,7.65,TB,K,K,2.468,2.652,3.060,0.0
92,93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,...,6.10,6.53,6.76,TB,K,K,2.440,2.612,2.704,0.0
93,94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,...,6.53,7.12,6.97,K,K,K,2.612,2.848,2.788,0.0
94,95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,...,6.10,6.71,6.68,TB,K,K,2.440,2.684,2.672,0.0
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

4. Thống kê dữ liệu thiếu cho cột dân tộc và hiệu chỉnh dữ liệu thiếu như sau: Mặc định thiếu
thì điền giá trị 0.

Hướng dẫn
   
    1. Lập bảng tần số, tần suất để khảo sát dữ liệu thiếu, bao nhiêu dữ liệu riêng biệt (pandas unique)
    2. Thực hiện thay thế dữ liệu thiếu bằng phương pháp điền dữ liệu 0

In [7]:
dftuyensinh['DT'] = dftuyensinh['DT'].fillna(0)
dftuyensinh['DT']

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
     ...
95    0.0
96    0.0
97    0.0
98    0.0
99    0.0
Name: DT, Length: 100, dtype: float64

5. Thống kê dữ liệu thiếu cho biến T1 và hiệu chỉnh dữ liệu, lưu ý việc thay thế dữ liệu thiếu sử
dụng phương pháp Mean.

In [8]:
dftuyensinh.loc[:, 'T1'] = dftuyensinh['T1'].fillna(dftuyensinh['T1'].mean())
dftuyensinh

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

6. Hãy thực hiện xử lý lần lượt tất cả dữ liệu thiếu cho các biến về điểm số còn lại.

In [9]:
diem_con_lai = dinh_luong
for col in diem_con_lai:
    dftuyensinh[col] = dftuyensinh[col].fillna(dftuyensinh[col].mean())
dftuyensinh

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

7. Tạo các biến TBM1, TBM2, TBM3 tương ứng với trung bình môn của các năm lớp 10, 11 và12.

• Công thức tính: TBM = (T*2 + L + H + S + V*2 + X + D + N) / 10

In [10]:
dftuyensinh['TBM1'] = (dftuyensinh['T1']*2 + dftuyensinh['L1'] + dftuyensinh['H1'] + dftuyensinh['S1'] + dftuyensinh['V1']*2 + dftuyensinh['X1'] + dftuyensinh['D1'] + dftuyensinh['N1']) / 10
dftuyensinh['TBM2'] = (dftuyensinh['T2']*2 + dftuyensinh['L2'] + dftuyensinh['H2'] + dftuyensinh['S2'] + dftuyensinh['V2']*2 + dftuyensinh['X2'] + dftuyensinh['D2'] + dftuyensinh['N2']) / 10
dftuyensinh['TBM3'] = (dftuyensinh['T6']*2 + dftuyensinh['L6'] + dftuyensinh['H6'] + dftuyensinh['S6'] + dftuyensinh['V6']*2 + dftuyensinh['X6'] + dftuyensinh['D6'] + dftuyensinh['N6']) / 10
dftuyensinh

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

8. Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1,TBM2 và TBM3 cho từng năm lớp 10, 11, 12 như sau:

• Nhỏ hơn 5.0 xếp loại: yếu (kí hiệu là Y)

• Từ 5.0 đến dưới 6.5: trung bình (kí hiệu là TB)

• Từ 6.5 đến dưới 8.0: khá (kí hiệu là K)

• Từ 8.0 đến dưới 9.0: giỏi (kí hiệu là G)

• Từ 9.0 trở lên: xuất sắc (kí hiệu là XS)

In [11]:
def TB_Mon(score):
    return ('Y' if score < 5.0 else
            'TB' if score < 6.5 else
            'K' if score < 8.0 else
            'G' if score < 9.0 else 'XS')

dftuyensinh['XL1'] = dftuyensinh['TBM1'].apply(TB_Mon)
dftuyensinh['XL2'] = dftuyensinh['TBM2'].apply(TB_Mon)
dftuyensinh['XL3'] = dftuyensinh['TBM3'].apply(TB_Mon)
dftuyensinh

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

9. Tạo các biến US_TBM1, US_TBM2 và US_TBM3 để chuyển điểm trung bình các năm lớp
10, 11 và 12 từ thang điểm 10 của Việt Nam sang thang điểm 4 của Mỹ. Sử dụng phương
pháp Min-Max Normalization

In [12]:
def TB_MonUS(x):
    return (x - x.min()) / (x.max() - x.min()) * 4

dftuyensinh['US_TBM1'] = TB_MonUS(dftuyensinh['TBM1']).round(3)
dftuyensinh['US_TBM2'] = TB_MonUS(dftuyensinh['TBM2']).round(3)
dftuyensinh['US_TBM3'] = TB_MonUS(dftuyensinh['TBM3']).round(3)
dftuyensinh

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.931,3.029,2.537,0.0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,0.644,1.019,0.320,0.0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,1.713,0.932,1.429,1.0
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.149,0.757,2.389,0.0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.436,1.883,2.514,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,K,K,K,3.356,2.913,2.331,0.0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Y,TB,TB,0.881,0.709,1.829,0.0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,K,K,K,2.980,3.320,3.291,1.0
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Y,Y,TB,0.109,0.291,0.571,0.0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,TB,TB,TB,1.208,1.262,1.211,0.0

10. Tạo biến kết quả xét tuyển (kí hiệu là KQXT) nhằm xác định sinh viên đậu (giá trị “1”) và rớt ( giá trị “0”) vào các khối dựa trên điểm DH1, DH2 và DH3 như sau

• Với khối A, A1 nếu [(DH1*2 + DH2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu,
ngược lại là rớt

• Với khối B nếu [(DH1 + DH2*2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược
lại là rớt

• Với khối khác nếu [(DH1+ DH2 + DH3)/3] lớn hơn hoặc bằng 5.0 thì đậu, ngược
lại là rớt

In [13]:
def KQ_xettuyen(row):
    if row['KT'] in ['A', 'A1']:
        return 1 if (row['DH1']*2 + row['DH2'] + row['DH3']) / 4 >= 5.0 else 0
    elif row['KT'] == 'B':
        return 1 if (row['DH1'] + row['DH2']*2 + row['DH3']) / 4 >= 5.0 else 0
    else:
        return 1 if (row['DH1'] + row['DH2'] + row['DH3']) / 3 >= 5.0 else 0

dftuyensinh['KQXT'] = dftuyensinh.apply(KQ_xettuyen, axis=1)
dftuyensinh

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.931,3.029,2.537,0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,0.644,1.019,0.320,0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,1.713,0.932,1.429,1
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.149,0.757,2.389,0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.436,1.883,2.514,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,K,K,K,3.356,2.913,2.331,0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Y,TB,TB,0.881,0.709,1.829,0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,K,K,K,2.980,3.320,3.291,1
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Y,Y,TB,0.109,0.291,0.571,0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,TB,TB,TB,1.208,1.262,1.211,0

11. Lưu trữ dữ liệu xuống ổ đĩa thành file processed_dulieuxettuyendaihoc.csv

In [14]:
dftuyensinh.to_csv('processed_dulieuxettuyendaihoclab1.csv', index=False)